// src/constants/activity.ts

export const ACTIVITY_ACTIONS = {
  // Trip actions
  TRIP_CREATED: "TRIP_CREATED",
  TRIP_ASSIGNED: "TRIP_ASSIGNED",
  TRIP_ACCEPTED: "TRIP_ACCEPTED",
  TRIP_REJECTED: "TRIP_REJECTED",
  TRIP_STARTED: "TRIP_STARTED",
  TRIP_ENDED: "TRIP_ENDED",
  TRIP_CANCELLED: "TRIP_CANCELLED",
  TRIP_STATUS_CHANGED: "TRIP_STATUS_CHANGED",
  TRIP_UPDATED: "TRIP_UPDATED",
  // Driver actions
  DRIVER_CREATED: "DRIVER_CREATED",
  DRIVER_UPDATED: "DRIVER_UPDATED",
  DRIVER_STATUS_CHANGED: "DRIVER_STATUS_CHANGED",
  DRIVER_CLOCK_IN: "DRIVER_CLOCK_IN",
  DRIVER_CLOCK_OUT: "DRIVER_CLOCK_OUT",
  // Staff actions
  STAFF_CREATED: "STAFF_CREATED",
  STAFF_UPDATED: "STAFF_UPDATED",
  STAFF_STATUS_CHANGED: "STAFF_STATUS_CHANGED",
  STAFF_CLOCK_IN: "STAFF_CLOCK_IN",
  STAFF_CLOCK_OUT: "STAFF_CLOCK_OUT",
  // Complaint actions
  COMPLAINT_CREATED: "COMPLAINT_CREATED",
  COMPLAINT_RESOLVED: "COMPLAINT_RESOLVED",
  COMPLAINT_STATUS_CHANGED: "COMPLAINT_STATUS_CHANGED",
  // Leave actions
  LEAVE_REQUESTED: "LEAVE_REQUESTED",
  LEAVE_APPROVED: "LEAVE_APPROVED",
  LEAVE_REJECTED: "LEAVE_REJECTED",
  LEAVE_CANCELLED: "LEAVE_CANCELLED",
  // Rating actions
  RATING_SUBMITTED: "RATING_SUBMITTED",
  // Attendance actions
  ATTENDANCE_RECORDED: "ATTENDANCE_RECORDED",
  // Other
  CUSTOMER_CREATED: "CUSTOMER_CREATED",
  CUSTOMER_UPDATED: "CUSTOMER_UPDATED",
  FRANCHISE_CREATED: "FRANCHISE_CREATED",
  FRANCHISE_UPDATED: "FRANCHISE_UPDATED",
  FRANCHISE_STATUS_CHANGED: "FRANCHISE_STATUS_CHANGED",
} as const;

export const ACTIVITY_ENTITY_TYPES = {
  TRIP: "TRIP",
  DRIVER: "DRIVER",
  STAFF: "STAFF",
  CUSTOMER: "CUSTOMER",
  FRANCHISE: "FRANCHISE",
  COMPLAINT: "COMPLAINT",
  LEAVE_REQUEST: "LEAVE_REQUEST",
  RATING: "RATING",
  ATTENDANCE: "ATTENDANCE",
  OTHER: "OTHER",
} as const;

export const ACTIVITY_ERROR_MESSAGES = {
  ACTIVITY_NOT_FOUND: "Activity log not found",
} as const;
