import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import StoreProvider from "./StoreProvider";
import { ToastProvider } from "@/components/ui/toast";
import { TokenRefreshProvider } from "@/components/auth/TokenRefreshProvider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <StoreProvider>
          <ToastProvider>
            <TokenRefreshProvider>
              {children}
            </TokenRefreshProvider>
          </ToastProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
