export const PENALTIES_ROUTES = {
    LIST: '/penalties',
    CREATE: '/penalties/create',
    EDIT: '/penalties/edit',
    APPLY: '/penalties/apply',
} as const;

export const PENALTIES_API_ENDPOINTS = {
    LIST: '/penalties',
    CREATE: '/penalties',
    UPDATE: '/penalties',
    DELETE: '/penalties',
    GET_BY_ID: '/penalties',
    APPLY_TO_DRIVER: '/penalties/apply',
    DRIVER_PENALTIES: '/penalties/driver',
} as const;

export const PENALTIES_STRINGS = {
    TITLE: 'Penalties Management',
    LIST_TITLE: 'Penalties & Deductions',
    CREATE_TITLE: 'Create New Penalty',
    EDIT_TITLE: 'Edit Penalty',
    APPLY_TITLE: 'Apply Penalty to Driver',
    NAME: 'Penalty Name',
    NAME_PLACEHOLDER: 'Enter penalty name',
    NAME_REQUIRED: 'Penalty name is required',
    AMOUNT: 'Amount',
    AMOUNT_PLACEHOLDER: 'Enter amount',
    AMOUNT_REQUIRED: 'Amount is required',
    AMOUNT_INVALID: 'Amount must be a positive number',
    DESCRIPTION: 'Description',
    DESCRIPTION_PLACEHOLDER: 'Enter description (optional)',
    TYPE: 'Type',
    TYPE_PENALTY: 'Penalty',
    TYPE_DEDUCTION: 'Deduction',
    ACTIONS: 'Actions',
    EDIT: 'Edit',
    DELETE: 'Delete',
    APPLY: 'Apply to Driver',
    CREATE_NEW: 'Create New Penalty',
    NO_PENALTIES: 'No penalties found',
    SEARCH_PLACEHOLDER: 'Search penalties...',
    TARGET_TYPE: 'Apply To',
    TARGET_TYPE_DRIVER: 'Driver',
    TARGET_TYPE_STAFF: 'Staff',
    TARGET_TYPE_REQUIRED: 'Please select target type',
    DRIVER_SELECT: 'Select Driver',
    STAFF_SELECT: 'Select Staff',
    DRIVER_REQUIRED: 'Please select a driver',
    STAFF_REQUIRED: 'Please select a staff member',
    REASON: 'Reason',
    REASON_PLACEHOLDER: 'Enter reason for applying this penalty',
    REASON_REQUIRED: 'Reason is required',
    APPLY_SUCCESS: 'Penalty applied successfully',
    APPLY_ERROR: 'Failed to apply penalty',
    CREATE_SUCCESS: 'Penalty created successfully',
    CREATE_ERROR: 'Failed to create penalty',
    UPDATE_SUCCESS: 'Penalty updated successfully',
    UPDATE_ERROR: 'Failed to update penalty',
    DELETE_SUCCESS: 'Penalty deleted successfully',
    DELETE_ERROR: 'Failed to delete penalty',
    DELETE_CONFIRM: 'Are you sure you want to delete this penalty?',
    SAVE: 'Save',
    CANCEL: 'Cancel',
    SUBMIT: 'Submit',
    LOADING: 'Loading...',
} as const;

export const PENALTY_TYPES = {
    PENALTY: 'PENALTY',
    DEDUCTION: 'DEDUCTION',
} as const;
