-- CreateEnum (only if it doesn't exist)
DO $$ BEGIN
    CREATE TYPE "CarType" AS ENUM ('MANUAL', 'AUTOMATIC', 'PREMIUM_CARS', 'LUXURY_CARS', 'SPORTY_CARS');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- AlterTable
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "driverCode" TEXT;
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "password" TEXT;
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "emergencyContactName" TEXT;
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "emergencyContactPhone" TEXT;
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "emergencyContactRelation" TEXT;
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "state" TEXT;
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "pincode" TEXT;
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "licenseNumber" TEXT;
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "licenseExpDate" TIMESTAMP(3);
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "bankAccountName" TEXT;
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "bankAccountNumber" TEXT;
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "bankIfscCode" TEXT;
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "aadharCard" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "license" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "educationCert" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "previousExp" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "carTypes" TEXT;
ALTER TABLE "Driver" ADD COLUMN IF NOT EXISTS "createdBy" INTEGER;

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "Driver_email_key" ON "Driver"("email");
CREATE UNIQUE INDEX IF NOT EXISTS "Driver_driverCode_key" ON "Driver"("driverCode");

-- AddForeignKey (optional - only if User table exists with Int id)
-- ALTER TABLE "Driver" ADD CONSTRAINT "Driver_createdBy_fkey" FOREIGN KEY ("createdBy") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
